#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
  path: /
  controller: App\Controller\HomeController::index

invoice:
  path: /invoice/{user_cooking_time_id}
  controller: App\Controller\InvoiceController::invoice
  methods: ['GET']
  requirements:




